### PR TITLE
logging

### PR DESCRIPTION
**Pull request by ozzy1323232**
be aware that this will remove debug print(), and only keep neccessary logs

### CODE REVIEW

**Review by DeltaO3 — COMMENTED** [review]
Having not gone into the codebase to test, this looks like its fineand i assume wont break anything major, but I wont approve yet just in case

**Review by ipr17 — APPROVED** [review]
Works for me, happy for someone else to review as well if needed.

**Comment by livvy10** [comment]
had a look, and looking good!
some things I noted:
- /student_suggestions is logged each time, meaning everytime a user types a letter into the student sign in it is recorded - feels like this could bloat out the log file and make it harder to find things you do want logged
- not all the print statements have been changed to logging so there are some print statements that are still printing as before but also not in the log file, some I found are:
CSV export
Removing session cookie
Attendance record updated successfully
Adding a student
Adding a unit to the coordinator
Checking unit validity and date validity (when setting up a unit)

I'm not going to request changes, if you get time it would be great but no stress

The logging is set up to follow a good form and write to a file, and is not too hard to add another log message I believe, so this is still very useful as Adrian can easily add whatever logs he needs

**Comment by Ay1tsMe** [comment]
This is better than it was before but there isnt much details on what is actually logged. For each of these lines, there should be details on what user account is actually making the logs. IP address isnt enough because multiple users can be using it from the same IP
```
127.0.0.1 2024-10-13 14:18:47 - /sign_all_out

127.0.0.1 2024-10-13 14:18:47 - /sign_all_out Successful

127.0.0.1 2024-10-13 14:19:19 - /admin

127.0.0.1 2024-10-13 14:19:20 - /unitconfig

127.0.0.1 2024-10-13 14:19:23 - /export

127.0.0.1 2024-10-13 14:19:23 - /export Attempting to Export Database...
```
And for each input there should be details on what input they have made. Like for example if I add a comment for a student, it shows this:
```
Attendance record for student ID 8 updated successfully.
127.0.0.1 2024-10-13 14:22:52 - /edit_student_details Updated

127.0.0.1 2024-10-13 14:22:52 - /home - Session : Pizza
```
Instead it should show the exact comment that was submitted. Not that it was updated.

Also when logging signing in students, if they are already enrolled in the session, then there log in wont be logged. It only logs if they are being assigned to a brand new session.

Also, when a user logs in, it prints the password that was submitted and then the salted encrypted in the terminal. This shouldnt be displayed AT ALL. I

I think we have little time to make it better so its fine to merge once you the print commands for passwords are removed. Everything else can just be improved in a later version if there is one.

**Review by Ay1tsMe — CHANGES_REQUESTED** [review]
Delete print statements that show the password submitted and the salted version of that password

**Review by Ay1tsMe — APPROVED** [review]

**Pull request merged**
