### PR TITLE
103 sprint 3 database schema cleanup

### PR DESCRIPTION
**Pull request by livvy10**
Changed the db:
- userType to string type ("admin", "facilitator", "coordinator")
- remove uwaID from User
- add email field (string) to User - now the unique identifier for users
- remove active field from Unit
- make unitName in Unit non-nullable
- consent in Student and consent_given in Attendance are now strings ("yes", "no", "not required")

I've then made the necessary changes to all code to ensure they work with the new schema

And I've also added in a couple of other small fixes including:
making the current user Id's the facilitator Id that signed them in
making sure consent not required works (it still displays on home page but doesn't let you have it as anything else except not required)
ensuring edit student details updates the consent_given in that attendance record

### CODE REVIEW

**Comment by livvy10** [comment]
Keep in mind you will have to create a new db, and use the new factilitator file (which has email)
Also when testing, please test out every feature.
I have tested everything except the createadmin.py (as I couldn't figure out the dotenv thingy), so if someone can please test that that would be great (I'm pretty sure it should work, I just changed uwaid to email everywhere)

**Review by DeltaO3 — COMMENTED** [review]
Mostly! works for me.
As mentioned on discord, i cant seem to change my  unit in updateunit if im part of multiple units. unsure if this was always a bug, or if thats intended, but its worth noting. Otherwise looks good to me.

**Review by DeltaO3 — APPROVED** [review]
Previous comment not relevent anymore, approved, but someone else _please_ review

**Comment by ipr17** [comment]
Looks great, I couldn't find any bugs so I'm going to merge now!

**Pull request merged**
