### PR TITLE
Sprint 3 - Add facilitator name to ExportCSV and link export to `userID`'s

### PR DESCRIPTION
**Pull request by Ay1tsMe**
Addressed the changes for exporting the database that Adrian brought up. Things that have been changed:
- `attendancerecordCOLUMNS.csv` now displays the facilitator that signed that student in. Current format is like this with `FacilitatorName` being the Full Name of the facilitator: 
```
[sessionName][FacilitatorName]signInTime;signOutTime
```
- Removed the `passwordHash` column from the `users.csv`. Only way to view the password hash is to query the database yourself.
- The Export database is now linked to `userID`'s. So the only csv's that a user can export is the data that is linked to their `userID`.

Example of new behaviour:
```
# When an admin exports the database: 
They will be able to see every csv along with it's data.

# When a coordinator exports the database:
They will only be able to see data in the csv's that are associated with them. 
The student lists, attendance, unit information and more will only display if the coordinator is in control of that unit. 
Coordinators will also not receive the `user.csv` file 
```

### CODE REVIEW

**Review by DeltaO3 — APPROVED** [review]
Seems good to me

**Comment by Ay1tsMe** [comment]
Added the ability to select a unit. This should be done now. Maybe someone might wanna change styling if they dont like it. But overall functionality should work. Please test before merging

**Review by DeltaO3 — CHANGES_REQUESTED** [review]
Many changes to CSS file that should not be there.

**Review by DeltaO3 — APPROVED** [review]
Working on other unit rn, butchanging back to approved as a run over the code shouldnt break anything with my testing (so as not to disrupt the PR flow)

**Review by livvy10 — CHANGES_REQUESTED** [review]
Looking good! couple of things:
- I don't think token should be included in users to improve security (as it can be used to change a user's password i think, regardless it's not useful info to the coordinator)
- instead of <session date/time>_Grade being the column name it should be something else e.g.<session date/time>_StudentDetails as it includes the comments (or maybe separate columns for marks and comments? that might make it easier to analyse marks, although then a LOT of columns would be added so up to you)
- i think we need to included the consent_given part of attendance record as they might need this (in case a student says yes and then changes to no), probs add it with the marks and comments 
- i think something is happening where a column with _Afternoon is always appended for each date that there was a session, but this is not an actual session. it isn't in the sessions csv, and the unit i tested for never even had session times of morning/afternoon, only hours
- and yes i think you said this but in an admin account exporting all units exports all units ever, rather than just the user's own units they are coordinator of. for coordinator accounts they only download their own which is good

facilitator name looks good

**Comment by Ay1tsMe** [comment]
> Looking good! couple of things:
> 
> * I don't think token should be included in users to improve security (as it can be used to change a user's password i think, regardless it's not useful info to the coordinator)
> * instead of <session date/time>_Grade being the column name it should be something else e.g.<session date/time>_StudentDetails as it includes the comments (or maybe separate columns for marks and comments? that might make it easier to analyse marks, although then a LOT of columns would be added so up to you)
> * i think we need to included the consent_given part of attendance record as they might need this (in case a student says yes and then changes to no), probs add it with the marks and comments
> * i think something is happening where a column with _Afternoon is always appended for each date that there was a session, but this is not an actual session. it isn't in the sessions csv, and the unit i tested for never even had session times of morning/afternoon, only hours
> * and yes i think you said this but in an admin account exporting all units exports all units ever, rather than just the user's own units they are coordinator of. for coordinator accounts they only download their own which is good
> 
> facilitator name looks good

To address your points:
1. Token has been removed
2. I think we should keep it _Grade because thats how I'm following Adrians sample mock database. I think keeping it how its formatted is safest option
3. consent_given has been added and works for each attendance record
4. I'm not sure what youre experiencing. When I create a morning session on the following day, it doesn't create an _Afternoon session. Although I think this might be something to do with unit using time instead of morning afternoon. I think this would take to long to fix and I'm going on the assumption that Adrian is going to use morning afternoon sessions and not the time ones. Therefore he shouldnt experience this? I believe this is only a problem in the COLUMN csv so other unit coordinators can use the other one that works.
5. Fixed, admin cant export all units, only the units they are assigned to

**Review by livvy10 — APPROVED** [review]
awesome, looks good, points 1,3,5 all appear to be working as intended
disagree a lil on point 2 but it's not a bit deal so happy to go with whatever you think
when I tried recreating the bug in point 4 it didn't happen so I'm hoping it was a mistake the first time! sorry if it was haha

if it's easy to add the student's consent as a column to each student row (not sure if you had that earlier??) I feel like that would be good considering I think Adrian's intention was for the columns csv one to be the only one he uses / needed. however the data is all in students so I feel like it's not a big deal either way esp considering you have other more important stuff

one thing I did notice is that if a student attended multiple sessions in the same session time (e.g. pipeworks morning and cad morning on a given day), only one of them is recorded in the columns csv file. I thought I remembered him having multiple attendances to different sessions all appended - do you have his sample csv columns somewhere?
I'm not sure if this is just because Adrian didn't have a remove student so if a student went to the wrong class first, he would see both attendances and figure out what had happened, but that students should only ever be in one session for a given time. However, even though we have a remove student button, I feel that if a student goes to the wrong session, then leaves but the facilitator doesn't remove them accidentally (because they don't realise the impact), then they go to a different one but that genuine attendance record is hidden (although from testing I believe it is the most recent one that is shown, not 100% sure though)
Flagging but not sure if it is an issue as I don't know if multiple students can attend multiple sessions in the same session time or not (and whether he would want all records displayed regardless)

Approving because I'm aware we are getting close to the due date and don't want to be holding anything up, plus only minor things and overall it looks good

**Pull request merged**
