### PR TITLE
Added User Stories Sprint 3

### PR DESCRIPTION
**Pull request by Jimbos21**
Added pdf.

### CODE REVIEW

**Review by DeltaO3 — CHANGES_REQUESTED** [review]
Look pretty good, a few things:
- Typo : "As a user I would like the data I have imputed" - inputted.
- "I should only be able to access settings and tools I require to complete my job" is a bit vague, i believe you are talking about user validation and such here?
- "As an Administrator I should be able to give the right to add units to Unit Coordinators" - dont UC's have this right by default?

Can't think of any other stories we need off the top of my head, but may come up with more later.

**Comment by Jimbos21** [comment]
> Look pretty good, a few things:
> 
>     * Typo : "As a user I would like the data I have imputed" - inputted.
> 
>     * "I should only be able to access settings and tools I require to complete my job" is a bit vague, i believe you are talking about user validation and such here?

Yes that is what I tried to make into a story, pretty much that unit coordinators can add units but liek facilitators can't.
> 
>     * "As an Administrator I should be able to give the right to add units to Unit Coordinators" - dont UC's have this right by default?

What I meant by this was that Administrators add unit coordinator accounts that can ad dthere own units I can try reword it.

**Comment by livvy10** [comment]
Some other ideas to potentially include:
- users being able to get session times suggested to them based on the current time
- unit coordinators would want their units to automatically disable after the end date so that facilitators can't still access old units

Adrian also has talked about automatically deleting data for the whole unit like 6 months after the end date of the unit, but i'd be scared to implement this tbh and we can't really test it exactly so probs don't include this one

**Review by DeltaO3 — COMMENTED** [review]
image
need to, not too. can quickly fix this typo myself later tho

Do we also want to add something about search functionality?

**Review by DeltaO3 — APPROVED** [review]

**Pull request merged**
