### PR TITLE
104 sprint 3 remove entries from database after some period of time

### PR DESCRIPTION
**Pull request by ozzy1323232**
This is a html <table> page that lists all units that ave expired (1 year ago). 

It deletes from all tables any reference to the unit

### CODE REVIEW

**Comment by DeltaO3** [comment]
I think you may have somehow misunderstood the issue and what was being asked.

I'm pretty sure we dont want to have a cheap solution of a new front-end page for this purpose. There are many reasons why this would be  a bad idea imo (Have to manually do it, no one will think to do it, its a security flaw, clogs the navbar etc.)

The better approach (?) would be to have some kind of script that performs the operation, which we can setup to be run, say, every day at midnight by the server. Obviously one would have to ensure the script isn't runnable by incorrect users (not entirely sure how this works from a security standpoint, but if you can edit this script you can edit any script and just make it delete the entire database when run anyway, so its not a unique flaw to this kind of approach).
We understand that this is difficult - this is what we were talking about in the meeting and you were being dismissive as to the difficulty of the task at hand. This issue may require a bit of discussion with those hosting (I'm not sure if adam or isabella are more in charge of that at this moment in time)

For the sake of code readability, database operations should to the best extent possible be contained in databases.py, mainly for code consistency and cleanliness.

**Comment by ozzy1323232** [comment]
> I think you may have somehow misunderstood the issue and what was being asked.
> 
> I'm pretty sure we dont want to have a cheap solution of a new front-end page for this purpose. There are many reasons why this would be a bad idea imo (Have to manually do it, no one will think to do it, its a security flaw by extension, clogs the navbar etc.)
> 
> The better approach (?) would be to have some kind of script that performs the operation, which we can setup to be run, say, every day at midnight by the server. Obviously one would have to ensure the script isn't runnable by incorrect users although it shouldn't matter much here due to just deleting old entries (not entirely sure how this works from a security standpoint, but if you can edit this script you can edit any script and just make it delete the entire database when run anyway, so its not a unique flaw to this kind of approach). We understand that this is difficult - this is what we were talking about in the meeting and you were being dismissive as to the difficulty of the task at hand. This issue may require a bit of discussion with those hosting (I'm not sure if adam or izzy are more in charge of that at this moment in time)
> 
> For the sake of code readability, database operations should to the best extent possible be contained in databases.py, mainly for code consistency and cleanliness.
> 
> Additionally, display of units is already being done by a seperate issue (currently under @Jimbos21 oversight?), which is most of what this frontend component is. If this really was the approach we ended up going with, we would just put it there and have units sorted by date with some splitter akin to what LMS has.
> 
> I'm also 70% certain that cascading deletes ([example](https://www.geeksforgeeks.org/sqlalchemy-cascading-deletes/) ) mean you dont need to manually delete all the corresponding entries. Not _100%_ certain here but its something to look into to avoid having to have multiple paragraphs of code deleting each manually.

done, so it will run the script for deleting expired units everytime someone logs in, and i have taken it from the navbar and deleted the html file

**Comment by ozzy1323232** [comment]
Points,

- I used Flask APSchedule to make a deletion script run every 24 Hours.
- It will delete evrything related to a unit older than 1 year
- Init.py has added features for the scheduling
@DeltaO3

**Review by DeltaO3 — COMMENTED** [review]
This is much better! I tested it by changing the time form hours=24 to minutes=2 (for testing), and it seems to run, i think. Not approving because I want someone else to approve and merge (very important PR should 100% be double checked), but i think this is good enough.

**Review by DeltaO3 — APPROVED** [review]

**Comment by DeltaO3** [comment]
Just resolved a merge conflict with this branch from the new merge, but haven't checked that the functionality still works/ may have incorrectly done it

**Pull request merged**
