### PR TITLE
22 sprint 2 login page flask functionality

### PR DESCRIPTION
**Pull request by livvy10**
Created the login page, the form is created using forms.py.
The current test user credentials are: 
username: u1
password: p1
Successful login takes you to the session page. Errors in inputs (e.g. no data in field) are reported appropriately for now (we will need to discuss what error reporting we want so it can be standardised).

There are new requirements (wtforms) so please update from requirements.txt before running.
You will also need to set a secret key before starting the server (i.e. before running flask run) - check readme.md for details. I believe the Windows Command Prompt command I included is correct however, can someone please check that (I'm using linux). Also apparently using powershell has different commands but couldn't figure them out - not sure if this needs to also be added considering it is now the default one for Windows.

### CODE REVIEW

**Review by DeltaO3 — COMMENTED** [review]
Works as intended. One small thing - do we want to display login issues underneath (using flash iirc? or similar) - JS magic can be done to make failed attempts not reload the page but would probably be un-necessary this instance.

**Review by Ay1tsMe — APPROVED** [review]
Works for me.

**Review by DeltaO3 — APPROVED** [review]
In the interest of getting code into the repo, approving, but do look at above comments before deciding to merge :)

**Review by DeltaO3 — APPROVED** [review]
Re Approving after merge

**Pull request merged**
