### PR TITLE
130 sprint 3 consent hidden for sessions where unit does not require it

### PR DESCRIPTION
**Pull request by livvy10**
Removed consent from home page if not enabled
Removed consent and marks from student page if not enabled
Comments always there in student page but will display as "Multiple sign in/out time log" if not enabled (rather than Leave/edit comments when enabled)

Please let me know if you have any opinions about whether comments should be displayed as I have implemented as I wasn't sure but was just going off what Delta and I had discussed

### CODE REVIEW

**Review by DeltaO3 — APPROVED** [review]
mostly LGTM, should we call it something a bit more clear? Happy to merge as is and make a 5 minute PR on friday or smth if its faster?
Also should we add disabled to the comments field if no comments?

**Review by ipr17 — CHANGES_REQUESTED** [review]
This is an edge case, but I do think we should have proper error messages. I set the unit to no comments, but then left a random comment, and I get the flash message that no attendance record can be found for the student. I feel like this is not expected behaviour. 

I also tested the case where the user is signed in, signed out, signed back in, and the auto comment is left. As a facilitator, I could not remove or change this comment to display, for example, a different time. I assume this is not what we want, as we have left this field editable.

**Comment by DeltaO3** [comment]
I'm of the opinion that if comments are turned off, we add the disabled property to the form (using jinja conditionals)

**Comment by ipr17** [comment]
> I'm of the opinion that if comments are turned off, we add the disabled property to the form (using jinja conditionals). This prevents inputs

I like this idea

**Comment by livvy10** [comment]
Have incorporate feedback and made additional requested changes:
- comments box is now disabled if the comments are not enabled for the unit
- fixed the bug (the way i was doing it removed studentID - forms are so annoying to work with - from the student page form so it was not letting you save student details, I've used a different way now so this doesn't happen, the error message shouldn't come up now)
- comment suggestions are not displayed in student page if unit doesn't have comments enabled
- in addunit form comments default to being true/checked (the editunit form will correctly override this to be whatever the current unit's setting is)

**Review by ipr17 — APPROVED** [review]
Yep works for me now! Nice one.

**Pull request merged**
