### PR TITLE
132 sprint 3 facilitator account creation page

### PR DESCRIPTION
**Pull request by DeltaO3**
Made 3 pages: 
Landing page for creating an account (/create_account)
Forgot password page (/forgot_password)
Reset password page for landing after forgot password (/reset_password)

minimal functionality without emails is there.

### CODE REVIEW

**Comment by Ay1tsMe** [comment]
When creating a new account, it logs me into the new account but shows a previous session that was set up on another account. We would need some code that when logged into a new account, it prompts to create a brand new session rather than using the one in the cookies that was made with a different account.

**Comment by DeltaO3** [comment]
Should I work on this here, or is that in the scope of someone else?

**Comment by Ay1tsMe** [comment]
The bug is probably outside scope but still uncomfortable with approving yet. Need to ensure that there aren't any vulnerabilities when creating accounts.

**Comment by DeltaO3** [comment]
Vulnerabilities occur when logging in as a different account to. I think livvy is now dealing with this?

**Review by ipr17 — APPROVED** [review]
Looks great. Sorry this took me so long to review. Merging now.

**Pull request merged**
