### PR TITLE
73 sprint 2 session configuration backend functionality

### PR DESCRIPTION
**Pull request by livvy10**
This PR implements the configure session functionality (as in configuring a new session, which may or may not already exist). It does not update session configuration (e.g. realising you are in "morning when you should be in "afternoon" so updating the current session).

Summary:
- changed form to include session time (e.g. "Morning")
- changed the session form's select options to be based on the user's units to facilitate (for a user with multiple units the first units details are used)
- if the user changes the unit selected, the session names and session times change accordingly
- when a session is configured, if doesn't already exist, the session is added to the database

*This PR assumes a user with userID=1 exists and this is hard-coded in for testing so make sure that you have that in the db (otherwise I think it will crash)
To see the functionality, you want to have this user having units to facilitate (but it will still function without - an form with no select options will be served).

### CODE REVIEW

**Comment by livvy10** [comment]
something to check with Adrian: do we want the initial form to be as above, where the values are pre-filled? or do we want dummy placeholder to force users to pick each one more intentionally (rather than being pre-filled)?

**Comment by livvy10** [comment]
For Adam:
please note that I have changed the 'session_time' that you had to 'current_time' so that I could use session_time to be consistent with the db column names
I have also changed the value of the unit option fields so that it is (unitID, unitCode). Meaning the database name now has the unitID rather than the unitCode - sorry I tried so hard to make it the proper unit code name but couldn't figure it out. I wasn't sure how this would be used so didn't know whether it was essential to have the correct database name.
I hope this is ok, pls let me know if you want me to change anything

**Review by DeltaO3 — APPROVED** [review]
Think it works for me, but theres no feedback on the page / change to home page.

notes for later PRs
Should we have the inputs default to what the current session is ? im unsure

**Comment by ipr17** [comment]
Looks good to me as well, going to merge into main

**Pull request merged**
