### PR TITLE
sqlcipher

### PR DESCRIPTION
**Pull request by ozzy1323232**
Instructions:

- Only works on linux 
- Run the below shell commands:
- do the following https://charlesleifer.com/blog/encrypted-sqlite-databases-with-python-and-sqlcipher/
- and
- sudo apt-get -y install sqlcipher

### CODE REVIEW

**Review by Ay1tsMe — CHANGES_REQUESTED** [review]
Okay looks good and encrypts on rest.

Things that need fixing:
1. `requirements.txt` needs to be edited to include `sqlcipher3`
2. Password to encrypt database should be in the `.env` variable. Currently im not sure what the pragma key is to gain access to the `app.db`
3. README needs to be edited to state that dependency is to have sqlcipher installed and also some documentation on how to install it

**Comment by DeltaO3** [comment]
Would the requirements.txt need it, as its not a pip install?

**Comment by Ay1tsMe** [comment]
> Would the requirements.txt need it, as its not a pip install?

It is. The system needs sqlcipher installed to provide dependencies to pip. 

So in order for it to work on Linux you need to:
`sudo apt install sqlcipher`
Then do 
`pip install sqlcipher3`
If you don't install sqlcipher on the system it will throw errors when you try to install into your virtual environment.

**Comment by Ay1tsMe** [comment]
PR is ready to be reviewed. `app.db` will now encrypt at rest using the `DATABASE_PASSWORD` environment variable. You will need to delete `app.db` and rebuild using `flask db upgrade && python -m app.testdb`

Main thing to test before merging is if the web app runs and if you can decrypt the database. To open app.db:
```
sqlcipher app.db
```
To check if encrypted:
```
sqlite> .schema
Error: file is not a database
```
To decrypt `app.db`:
```
sqlite> PRAGMA key = 'DATABASE_PASSWORD';
ok
```
You should then be able to query the tables.
```
sqlite> .schema
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
CREATE TABLE session (
	"sessionID" INTEGER NOT NULL, 
	"unitID" INTEGER NOT NULL, 
	"sessionName" VARCHAR(50) NOT NULL, 
	"sessionTime" VARCHAR(50) NOT NULL, 
	"sessionDate" DATE NOT NULL, 
	CONSTRAINT pk_session PRIMARY KEY ("sessionID"), 
	CONSTRAINT "fk_session_unitID_unit" FOREIGN KEY("unitID") REFERENCES unit ("unitID")
);
CREATE TABLE IF NOT EXISTS "Units_Coordinators_Table" (
	"userID" INTEGER NOT NULL, 
	"unitID" INTEGER NOT NULL, 
	CONSTRAINT "pk_Units_Coordinators_Table" PRIMARY KEY ("userID", "unitID"), 
	CONSTRAINT "fk_Units_Coordinators_Table_unitID_unit" FOREIGN KEY("unitID") REFERENCES unit ("unitID"), 
	CONSTRAINT "fk_Units_Coordinators_Table_userID_user" FOREIGN KEY("userID") REFERENCES user ("userID")
);
CREATE TABLE IF NOT EXISTS "Units_Facilitators_Table" (
	"userID" INTEGER NOT NULL, 
	"unitID" INTEGER NOT NULL, 
	CONSTRAINT "pk_Units_Facilitators_Table" PRIMARY KEY ("userID", "unitID"), 
	CONSTRAINT "fk_Units_Facilitators_Table_unitID_unit" FOREIGN KEY("unitID") REFERENCES unit ("unitID"), 
	CONSTRAINT "fk_Units_Facilitators_Table_userID_user" FOREIGN KEY("userID") REFERENCES user ("userID")
);
CREATE TABLE IF NOT EXISTS "attendance" (
	"attendanceID" INTEGER NOT NULL, 
	"sessionID" INTEGER NOT NULL, 
	"studentID" INTEGER NOT NULL, 
	"signInTime" TIME NOT NULL, 
	"signOutTime" TIME, 
	"facilitatorID" INTEGER NOT NULL, 
	marks VARCHAR(100), 
	comments VARCHAR(1000), 
	consent_given VARCHAR(50) NOT NULL, 
	CONSTRAINT pk_attendance PRIMARY KEY ("attendanceID"), 
	FOREIGN KEY("studentID") REFERENCES student ("studentID"), 
	FOREIGN KEY("sessionID") REFERENCES session ("sessionID"), 
	FOREIGN KEY("facilitatorID") REFERENCES user ("userID")
);
CREATE TABLE IF NOT EXISTS "student" (
	"studentID" INTEGER NOT NULL, 
	"studentNumber" VARCHAR(15) NOT NULL, 
	"firstName" VARCHAR(50) NOT NULL, 
	"lastName" VARCHAR(50) NOT NULL, 
	title VARCHAR(50) NOT NULL, 
	"preferredName" VARCHAR(50) NOT NULL, 
	"unitID" INTEGER NOT NULL, 
	consent VARCHAR(50) NOT NULL, 
	CONSTRAINT pk_student PRIMARY KEY ("studentID"), 
	FOREIGN KEY("unitID") REFERENCES unit ("unitID")
);
CREATE TABLE IF NOT EXISTS "unit" (
	"unitID" INTEGER NOT NULL, 
	"unitCode" VARCHAR(50) NOT NULL, 
	"unitName" VARCHAR(50) NOT NULL, 
	"studyPeriod" VARCHAR(50) NOT NULL, 
	"startDate" DATE NOT NULL, 
	"endDate" DATE NOT NULL, 
	"sessionNames" VARCHAR(2000) NOT NULL, 
	"sessionTimes" VARCHAR(2000) NOT NULL, 
	comments BOOLEAN NOT NULL, 
	marks BOOLEAN NOT NULL, 
	consent BOOLEAN NOT NULL, 
	"commentSuggestions" VARCHAR(2000), 
	CONSTRAINT pk_unit PRIMARY KEY ("unitID")
);
CREATE TABLE IF NOT EXISTS "user" (
	"userID" INTEGER NOT NULL, 
	"userType" VARCHAR(15) NOT NULL, 
	"firstName" VARCHAR(50), 
	"lastName" VARCHAR(50), 
	"passwordHash" VARCHAR(256) NOT NULL, 
	email VARCHAR(320) NOT NULL, 
	CONSTRAINT pk_user PRIMARY KEY ("userID"), 
	CONSTRAINT uq_user_email UNIQUE (email)
);
```

**Review by Ay1tsMe — APPROVED** [review]

**Comment by ipr17** [comment]
```
sqlite> PRAGMA key = 'DATABASE_PASSWORD';
ok
```

This does not happen for me. Do I need to do anything to get this to work? I followed your instructions but maybe I am misunderstanding. @Ay1tsMe

**Pull request merged**
