### PR TITLE
62 sprint 2 create modelspy

### PR DESCRIPTION
**Pull request by livvy10**
Models created and database initialised. Remember to reinstall from requirements.txt and follow readme instructions to create your own db (and further instructions on how to use migrations).

In models.py I have included String field lengths (apparently some dbs require String columns to have their size specified so it is good practice to put in). The way I chose the size was just picking a number that the field would have no chance of needing more than, but otherwise fairly random - some feedback on whether this is fine or what is normally meant to be done is appreciated.

Also after much discussion with some of the team after our meeting on Friday, and much thought and consideration today, I decided to go ahead with the current database schema design and did not add an additional Session information table (which could store additional details about session e.g. session length or specific session times). See the related issue for more details #62

### CODE REVIEW

**Review by DeltaO3 — APPROVED** [review]
LGTM! I'm not a database expert, but running the command seems to create the database, and all the fields seem good? I think 50 characters is a reasonable limit, I did a brief bit of research and that may be the best way to do it? other opinions welcome.

**Review by ozzy1323232 — APPROVED** [review]
Thankyou so much, you did a really good job. The database works perfectly.

**Comment by ozzy1323232** [comment]
actually sorry i just found some errors while creating the database funtions, can you replace code with 
from typing import List, Optional
from datetime import date, time
from sqlalchemy import ForeignKey, Column, Table, Integer, String
from sqlalchemy.orm import relationship, Mapped, mapped_column, DeclarativeBase
from app import db

# Define the base class for declarative models
class Base(DeclarativeBase):
    pass

# Define association tables before models
Units_Coordinators_Table = Table(
    'Units_Coordinators_Table',
    Base.metadata,
    Column('userID', Integer, ForeignKey('user.userID'), primary_key=True),
    Column('unitID', Integer, ForeignKey('unit.unitID'), primary_key=True)
)

Units_Facilitators_Table = Table(
    'Units_Facilitators_Table',
    Base.metadata,
    Column('userID', Integer, ForeignKey('user.userID'), primary_key=True),
    Column('unitID', Integer, ForeignKey('unit.unitID'), primary_key=True)
)

# Define the models
class User(Base):
    __tablename__ = 'user'
    
    userID: Mapped[int] = mapped_column(primary_key=True)
    uwaID: Mapped[int] = mapped_column(unique=True, nullable=False)
    firstName: Mapped[Optional[str]] = mapped_column(String(50))
    lastName: Mapped[Optional[str]] = mapped_column(String(50))
    passwordHash: Mapped[str] = mapped_column(String(256), nullable=False)
    type: Mapped[int] = mapped_column(nullable=False)   # 1 (admin), 2 (coordinator), 3 (facilitator)

    unitsCoordinate: Mapped[List['Unit']] = relationship(secondary=Units_Coordinators_Table, back_populates='coordinators')
    unitsFacilitate: Mapped[List['Unit']] = relationship(secondary=Units_Facilitators_Table, back_populates='facilitators')

class Unit(Base):
    __tablename__ = 'unit'
    
    unitID: Mapped[int] = mapped_column(primary_key=True)
    unitCode: Mapped[str] = mapped_column(String(50), nullable=False)
    unitName: Mapped[Optional[str]] = mapped_column(String(50))
    studyPeriod: Mapped[str] = mapped_column(String(50), nullable=False)
    active: Mapped[bool] = mapped_column(nullable=False)
    startDate: Mapped[date] = mapped_column(nullable=False)
    endDate: Mapped[date] = mapped_column(nullable=False)

    coordinators: Mapped[List[User]] = relationship(secondary=Units_Coordinators_Table, back_populates='unitsCoordinate')
    facilitators: Mapped[List[User]] = relationship(secondary=Units_Facilitators_Table, back_populates='unitsFacilitate')
    students: Mapped[List['Student']] = relationship()

    sessionNames: Mapped[str] = mapped_column(String(2000), nullable=False)     # | separated string
    sessionTimes: Mapped[str] = mapped_column(String(2000), nullable=False)     # | separated string
    comments: Mapped[bool] = mapped_column(nullable=False)
    marks: Mapped[bool] = mapped_column(nullable=False)
    consent: Mapped[bool] = mapped_column(nullable=False)
    commentSuggestions: Mapped[Optional[str]] = mapped_column(String(2000))     # | separated string

class Student(Base):
    __tablename__ = 'student'
    
    studentID: Mapped[int] = mapped_column(primary_key=True)
    studentNumber: Mapped[int] = mapped_column(nullable=False)
    firstName: Mapped[str] = mapped_column(String(50), nullable=False)
    lastName: Mapped[str] = mapped_column(String(50), nullable=False)
    title: Mapped[str] = mapped_column(String(50), nullable=False)
    preferredName: Mapped[str] = mapped_column(String(50), nullable=False)
    unitID: Mapped[int] = mapped_column(ForeignKey('unit.unitID'), nullable=False)
    consent: Mapped[int] = mapped_column(nullable=False)   # 0 (no), 1 (yes), -1 (consent not required)

class Session(Base):
    __tablename__ = 'session'
    
    sessionID: Mapped[int] = mapped_column(primary_key=True)
    unitID: Mapped[int] = mapped_column(ForeignKey('unit.unitID'), nullable=False)
    sessionName: Mapped[str] = mapped_column(String(50), nullable=False)
    sessionTime: Mapped[str] = mapped_column(String(50), nullable=False)
    sessionDate: Mapped[date] = mapped_column(nullable=False)

class Attendance(Base):
    __tablename__ = 'attendance'
    
    attendanceID: Mapped[int] = mapped_column(primary_key=True)
    sessionID: Mapped[int] = mapped_column(ForeignKey('session.sessionID'), nullable=False)
    studentID: Mapped[int] = mapped_column(ForeignKey('student.studentID'), nullable=False)
    signInTime: Mapped[time] = mapped_column(nullable=False)
    signOutTime: Mapped[time] = mapped_column()
    facilitatorID: Mapped[int] = mapped_column(ForeignKey('user.userID'), nullable=False)
    marks: Mapped[Optional[str]] = mapped_column(String(100))         # | separated string
    comments: Mapped[Optional[str]] = mapped_column(String(1000))     # | separated string
    consent_given: Mapped[int] = mapped_column(nullable=False)

**Comment by ozzy1323232** [comment]
[new 2.txt](https://github.com/user-attachments/files/16829233/new.2.txt)

I just had to change some stuff to get the functions working

**Comment by Ay1tsMe** [comment]
Looks good. I would like some test cases that populate and check for any errors. Right now I'm just manually changing schema and populating using `sqlite3` to see if everything works. I don't think there is any script to test the database but could be wrong. 

Otherwise we can just use https://github.com/DeltaO3/UWAttend---3200_27/pull/41 as a way to test when a refactor.

**Review by Ay1tsMe — APPROVED** [review]

**Comment by ozzy1323232** [comment]
> `sqlite3`

hey so far for me it also works, i populated most tables and it works. do you want me to send you a database.py function code so you can test the DB easier? i can send it now to you but as soon as this pull request is merged then im going to pull request the functions database.py

**Review by DeltaO3 — APPROVED** [review]

**Pull request merged**
